// <auto-generated />
using System;
using FichaCadastroAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaCadastroAPI.Migrations
{
    [DbContext(typeof(FichaCadastroContextDB))]
    [Migration("20230925231555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichaCadastroAPI.Model.DetalheModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("FichaId")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<bool>("Situacao")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.ToTable("Detalhe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2023, 9, 25, 20, 15, 54, 563, DateTimeKind.Local).AddTicks(380),
                            Feedback = "Bom trabalho!",
                            FichaId = 1,
                            Nota = 5,
                            Situacao = true
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2023, 9, 25, 20, 15, 54, 563, DateTimeKind.Local).AddTicks(393),
                            Feedback = "Precisa melhorar",
                            FichaId = 2,
                            Nota = 3,
                            Situacao = false
                        });
                });

            modelBuilder.Entity("FichaCadastroAPI.Model.FichaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Ficha");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2023, 9, 25, 20, 15, 54, 562, DateTimeKind.Local).AddTicks(9571),
                            DataNascimento = new DateTime(1998, 9, 25, 20, 15, 54, 562, DateTimeKind.Local).AddTicks(9590),
                            Email = "joao@example.com",
                            Nome = "João"
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2023, 9, 25, 20, 15, 54, 562, DateTimeKind.Local).AddTicks(9600),
                            DataNascimento = new DateTime(1978, 9, 25, 20, 15, 54, 562, DateTimeKind.Local).AddTicks(9603),
                            Email = "maria@example.com",
                            Nome = "Maria"
                        });
                });

            modelBuilder.Entity("FichaCadastroAPI.Model.TelephoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ative")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("FichaId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.ToTable("Telefone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ative = true,
                            DataCadastro = new DateTime(2023, 9, 25, 20, 15, 54, 563, DateTimeKind.Local).AddTicks(445),
                            Ddd = "123",
                            FichaId = 1,
                            Number = "555-1234"
                        },
                        new
                        {
                            Id = 2,
                            Ative = true,
                            DataCadastro = new DateTime(2023, 9, 25, 20, 15, 54, 563, DateTimeKind.Local).AddTicks(450),
                            Ddd = "456",
                            FichaId = 2,
                            Number = "555-5678"
                        });
                });

            modelBuilder.Entity("FichaCadastroAPI.Model.DetalheModel", b =>
                {
                    b.HasOne("FichaCadastroAPI.Model.FichaModel", "Ficha")
                        .WithMany("DetalheModels")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("FichaCadastroAPI.Model.TelephoneModel", b =>
                {
                    b.HasOne("FichaCadastroAPI.Model.FichaModel", "Ficha")
                        .WithMany("TelephoneModels")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("FichaCadastroAPI.Model.FichaModel", b =>
                {
                    b.Navigation("DetalheModels");

                    b.Navigation("TelephoneModels");
                });
#pragma warning restore 612, 618
        }
    }
}
